No connection adapters were found for '\x02https://www.facebook.com/groups/686099299903898'

HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://americas-considerable-sale-seo.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b9f88c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b9f882d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://verbal-kevin-land-called.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7c3067310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7c306c150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://packet-monaco-walls-spreading.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5ab6d6b8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5ab6d79790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Invalid URL '\\': No scheme supplied. Perhaps you meant https://\?
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://ir-mb-wu-boutique.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efc043ad650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efc043ac890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://vi-collectors-stats-florida.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a839cf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a839c910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url=https://trace-eagle-wireless-situated.trycloudflare.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f2dcce310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='api.shrtco.de', port=443): Max retries exceeded with url: /v2/shorten?url= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f2dcce950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
